version: '3.7'
services:
  db:
    image: postgres:12.5
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    restart: always
    user: root
    logging:
      options:
        max-size: '10k'
        max-file: '5'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
volumes:
  db-data:
    external: true
